# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 17:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import schedules.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(default='TYPE OF SHIFT', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(default='QUALIFICATION', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(default='NAME OF SCHEDULE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(default='NAME OF SHIFT', max_length=100)),
                ('day', schedules.fields.DayOfTheWeekField(choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], default=0, max_length=1)),
                ('start', models.TimeField(default=datetime.datetime(2018, 1, 1, 11, 0))),
                ('end', models.TimeField(default=datetime.datetime(2018, 1, 1, 12, 0))),
                ('workers_needed', models.IntegerField(default=1)),
                ('difficult', models.BooleanField(default=False)),
                ('flags', models.ManyToManyField(to='schedules.Flag')),
                ('qualifications', models.ManyToManyField(blank=True, to='schedules.Qualification')),
            ],
        ),
        migrations.CreateModel(
            name='Stapher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('first_name', models.CharField(default='FIRST NAME', max_length=100)),
                ('last_name', models.CharField(default='LAST NAME', max_length=100)),
                ('title', models.CharField(default='JOB TITLE', max_length=100)),
                ('gender', schedules.fields.GenderField(blank=True, choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Non-Binary'), ('3', 'Other')], max_length=1)),
                ('age', models.IntegerField(default=18)),
                ('class_year', models.IntegerField(default=2021)),
                ('summers_worked', models.IntegerField(default=0)),
                ('qualifications', models.ManyToManyField(blank=True, to='schedules.Qualification')),
            ],
        ),
        migrations.CreateModel(
            name='Staphing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Schedule')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Shift')),
                ('stapher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Stapher')),
            ],
        ),
    ]
