# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 00:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DEFAULT', max_length=100)),
                ('flag', models.CharField(default='', max_length=100)),
                ('start', models.DateTimeField(default=datetime.datetime.now)),
                ('end', models.DateTimeField(default=datetime.datetime.now)),
                ('qualifications', models.TextField(default='')),
                ('workers_needed', models.IntegerField(default=0)),
                ('difficult', models.BooleanField(default=False)),
                ('on_sunday', models.BooleanField(default=False)),
                ('on_monday', models.BooleanField(default=False)),
                ('on_tuesday', models.BooleanField(default=False)),
                ('on_wednesday', models.BooleanField(default=False)),
                ('on_thursday', models.BooleanField(default=False)),
                ('on_friday', models.BooleanField(default=False)),
                ('on_saturday', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stapher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='FIRST', max_length=100)),
                ('last_name', models.CharField(default='LAST', max_length=100)),
                ('title', models.CharField(default='DEFAULT', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('qualifications', models.TextField(default='')),
                ('age', models.IntegerField(default=18)),
                ('class_year', models.IntegerField(default=2018)),
                ('summers_worked', models.IntegerField(default=0)),
            ],
        ),
    ]
