# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 17:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import schedules.fields
import schedules.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TYPE OF SHIFT', max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NAME OF SHIFT', max_length=100)),
                ('day', schedules.fields.DayOfTheWeekField(choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], default=0, max_length=1)),
                ('start', models.TimeField(default=schedules.models.get_default_start_time)),
                ('end', models.TimeField(default=datetime.datetime.now)),
                ('qualifications', models.TextField(blank=True, default='')),
                ('workers_needed', models.IntegerField(default=1)),
                ('difficult', models.BooleanField(default=False)),
                ('flag', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedules.Flag')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stapher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='FIRST NAME', max_length=100)),
                ('last_name', models.CharField(default='LAST NAME', max_length=100)),
                ('title', models.CharField(default='JOB TITLE', max_length=100)),
                ('gender', schedules.fields.GenderField(blank=True, choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Non-Binary'), ('3', 'Other')], max_length=1)),
                ('qualifications', models.TextField(blank=True, default='')),
                ('age', models.IntegerField(default=18)),
                ('class_year', models.IntegerField(default=2021)),
                ('summers_worked', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
