# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import schedules.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='QUALIFICATION', max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='shift',
            name='end',
            field=models.TimeField(default=schedules.models.get_default_end_time),
        ),
        migrations.RemoveField(
            model_name='stapher',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='stapher',
            name='qualifications',
            field=models.ManyToManyField(to='schedules.Qualification'),
        ),
    ]
