# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 22:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
    ]
