# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 00:36
from __future__ import unicode_literals

from django.db import migrations
import schedules.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='day',
            field=schedules.fields.DayOfTheWeekField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0),
        ),
    ]
