# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end',
            field=models.TimeField(default=datetime.datetime(2018, 2, 8, 17, 0, 0, 721093)),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start',
            field=models.TimeField(default=datetime.datetime(2018, 2, 8, 16, 0, 0, 721064)),
        ),
    ]
