# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20180213_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='staphing',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
