# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-06 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(default='NAME OF SHIFT SET', max_length=100)),
            ],
        ),
    ]
