# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20180123_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='shift',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='schedules.Qualification'),
        ),
        migrations.AlterField(
            model_name='stapher',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='schedules.Qualification'),
        ),
    ]
