# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 00:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20180208_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end',
            field=models.TimeField(default=datetime.datetime(2018, 2, 8, 17, 0, 0, 482139)),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start',
            field=models.TimeField(default=datetime.datetime(2018, 2, 8, 16, 0, 0, 482112)),
        ),
    ]
