# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20180116_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='test',
        ),
        migrations.RemoveField(
            model_name='stapher',
            name='test',
        ),
    ]
