# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20180116_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stapher',
            name='class_year',
            field=models.IntegerField(default=0),
        ),
    ]
