# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import schedules.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_staphing_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='PARAMETER TITLE', max_length=100)),
                ('description', models.CharField(default='PARAMETER DESCRIPTION', max_length=500)),
                ('use', models.BooleanField(default=True)),
                ('rank', models.IntegerField(default=1, unique=True)),
                ('function_id', models.IntegerField(default=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_schedule', models.BooleanField(default=True)),
                ('auto_threshold', models.IntegerField(default=1)),
                ('tie_breaker', schedules.fields.TieBreakerField(choices=[('0', 'Choose one of the tied staphers randomly.'), ('1', 'Pick whoever won highest ranked parmeter.')], default=0, max_length=1)),
                ('parameters', models.ManyToManyField(to='schedules.Parameter')),
            ],
        ),
        migrations.RemoveField(
            model_name='staphing',
            name='active',
        ),
    ]
