# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 00:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20180208_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end',
            field=models.TimeField(default=datetime.datetime(2018, 2, 8, 12, 0)),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start',
            field=models.TimeField(default=datetime.datetime(2018, 2, 8, 11, 0)),
        ),
    ]
