# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20180117_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stapher',
            name='class_year',
            field=models.IntegerField(default=2018),
        ),
    ]
