# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20180123_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='flag',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.Flag'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='schedules.Qualification'),
        ),
        migrations.AlterField(
            model_name='stapher',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='schedules.Qualification'),
        ),
    ]
