# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-06 18:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20180606_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='excel_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 18, 6, 47, 247842, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 18, 6, 47, 247808, tzinfo=utc)),
        ),
    ]
