# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20180123_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='title',
            field=models.CharField(default='TYPE OF SHIFT', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='title',
            field=models.CharField(default='QUALIFICATION', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.Flag'),
        ),
    ]
