# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20180117_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stapher',
            name='gender',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='stapher',
            name='qualifications',
            field=models.TextField(default='none'),
        ),
    ]
