# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20180125_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stapher',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
