# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-06 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20180606_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='excel_updated',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='updated_on',
        ),
    ]
