# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_auto_20180131_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='flag',
        ),
        migrations.AddField(
            model_name='shift',
            name='flag',
            field=models.ManyToManyField(blank=True, to='schedules.Flag'),
        ),
    ]
