# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 03:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import schedules.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_auto_20180122_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='on_friday',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='on_monday',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='on_saturday',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='on_sunday',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='on_thursday',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='on_tuesday',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='on_wednesday',
        ),
        migrations.AddField(
            model_name='shift',
            name='day',
            field=schedules.fields.DayOfTheWeekField(choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], default=6, max_length=1),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='shift',
            name='flag',
            field=models.CharField(default='flag', max_length=100),
        ),
        migrations.AlterField(
            model_name='shift',
            name='qualifications',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
