# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-06 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_auto_20180606_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='excel_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
