# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-14 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20180606_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=1, unique=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Flag')),
            ],
        ),
        migrations.AddField(
            model_name='stapher',
            name='ranking',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shiftpreference',
            name='stapher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Stapher'),
        ),
    ]
