# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20180201_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='flag',
            new_name='flags',
        ),
    ]
