# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20180201_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='flags',
            field=models.ManyToManyField(to='schedules.Flag'),
        ),
    ]
