# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-14 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20180614_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stapher',
            name='ranking',
        ),
    ]
