# Generated by Django 4.2.30 on 2026-05-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_remove_stapher_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple_id', models.CharField(default='example@email.com', max_length=100)),
                ('password', models.CharField(default='••••••••', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='stapher',
            name='class_year',
            field=models.IntegerField(default=2029),
        ),
    ]
